name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Automatic deployment on push to main
  workflow_dispatch: # Allows manual deployment from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub Pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Change version as needed

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        run: npm run deploy
